# Sample API request.
# This can be tested inside Visual Studio Code using the REST Client extension.
POST http://localhost:3000/api
Content-Type: application/json

{
    "username": "apiUser",
    "password": "password123",
    "email": "user@example.com"
}