# Sample API request.
# This can be tested inside Visual Studio Code using the REST Client extension.
POST http://localhost:3000/api
Content-Type: application/x-www-form-urlencoded

username=craig
&password=password123
&email=craig@example.com